name: CI Logs to Discord

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v4

      - name: Rodar testes (exemplo)
        run: |
          echo "Executando testes..."

      - name: Notificar Discord
        if: always() # sempre notifica, mesmo se falhar
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

          # tÃ­tulo do embed
          title: >
            ${{ job.status == 'success' && 'âœ… Build Sucesso!' || 'âŒ Build Falhou!' }}

          # descriÃ§Ã£o detalhada
          description: |
            **RepositÃ³rio:** ğŸ“¦ ${{ github.repository }}
            **Status:** ${{ job.status == 'success' && 'ğŸŸ¢ Sucesso' || 'ğŸ”´ Erro' }}
            **Branch:** ğŸŒ± ${{ github.ref_name }}
            **Autor:** ğŸ‘¤ ${{ github.actor }}
            **Commit:** ğŸ”— [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            **ExecuÃ§Ã£o:** â–¶ï¸ [Ver no GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          # cor do embed (verde ou vermelho)
          color: ${{ job.status == 'success' && '3066993' || '15158332' }}
